server:
  port: 9000
spring:
  # Make sure to provide the application:name and profiles:active
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"  # We must use configserver here regardless of the name provided to application (configserver); optional is used when we want application to be started if case of issue as well.
  # Adding rabbitmq configuration
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# Refresh the MS when any changes occur (actuator/refresh). Here I'm including all the endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

###### To run in the browser at port 9000
#http://localhost:9000/h2-console
#http://localhost:9000/swagger-ui/index.html