server:
  port: 9000
spring:
  # Make sure to provide the application:name and profiles:active
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true  # To show the executed SQL inside the console
  sql:
    init:
      mode: always # Always run the schema sql commands
  config:
    import: "optional:configserver:http://localhost:8071/"  # We must use configserver here regardless of the name provided to application (configserver); optional is used when we want application to be started if case of issue as well.
  # Adding rabbitmq configuration
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

# Refresh the MS when any changes occur (actuator/refresh). Here I'm including all the endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
